runtime: go
api_version: go1.9

handlers:
- url: /delete
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

includes:
- secret.yml

env_variables:
  BASE_URL: "https://s.juntaki.com"
  RECAPTCHA_SITE_KEY: "6Lc48lAUAAAAAFehXaHNp0Ys-lS1iUfNtUXd_-eR"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^node_modules/(.*/)?
- generated
- src
- webpack.config.js
- ^(.*/)?.*\.json
