apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: url-shortener
        ports:
        - containerPort: 80
