apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: juntaki/url-shortener:latest
        ports:
        - containerPort: 8080
